name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: bash deps.sh

    - name: Make Resume
      run: make

    - name: Move files
      run: mkdir out && mv Angel_Ouellet.pdf README.md out

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: Output
          path: out

